In [6]:
import numpy as np
a = np.array([1,2,3,4])

# grab first 3 elements
a[:3]
# grab last two elements
a[-2:]
# every other element
a[::2]

### For 2 dimentional array
firstRow = np.array([0,1,2,3,4,5])
a = np.full((6,6),0)
a[0] = firstRow
a[1] = firstRow+10
a[2] = firstRow+20
a[3] = firstRow + 30
a[4] = firstRow + 40
a[5] = firstRow+50


a[0, 3:5]
a[4:, 4:]
a[:, 2]
a[2::2, ::2]

array([[20, 22, 24],
       [40, 42, 44]])

In [8]:
a = np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [11]:
# We can assign 99 to last 2 elements of a
a = np.array([0,1,2,3,4])
a[-2:] = 99; a
# a[-2:] = [-1,-2]


array([ 0,  1,  2, 99, 99])